modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="dragon_ball"
version="1.0.0"
displayName="Dragon Ball"
displayURL="https://trello.com/b/VlZ6VIut"
logoFile="logo.png"
credits="alex"
authors="alex"
description="Adds features from the Dragon Ball universe to minecraft!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dragon_ball]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.dragon_ball]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration